name:                Haskelyzer
version:             0.1.0.0
github:              "githubuser/Haskelyzer"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Haskelyzer#readme>

dependencies:
- base >= 4.7 && < 5
- parsec == 3.1.15.1
- text == 1.2.5.0
- indents == 0.5.0.1
- mtl == 2.2.2
- filepath == 1.4.2.1
- HUnit == 1.6.2.0
- hint == 0.9.0.6
- vector == 0.12.3.1
- template-haskell == 2.17.0.0
- async == 2.2.4

library:
  source-dirs: src
  ghc-options:
  - -ddump-splices

executables:
  Haskelyzer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskelyzer

tests:
  Haskelyzer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskelyzer
